os:
  - linux
dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
services:
  - xvfb

python:
  - "2.7"
  - "3.6"
  - "3.7"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install grequests requests requests_cache
  - pip install easydev>=0.9.36 beautifulsoup4 suds-jurko appdirs colorlog
  - pip install coveralls coverage
  # numpydoc --> install sphinx, not required. Was failing in feb 2020
  #sphinx-gallery
  - conda install -y pytest pytest-cov pytest-xdist pytest-timeout 
  - pip install pytest-rerunfailures
  - pip install .


# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=60 test/ --cov=bioservices --cov-report term-missing --timeout 300 -n 1

after_success: coveralls
